import { connectToDatabase } from '@/lib/database/mongodb'

export async function up(): Promise<void> {
  const db = await connectToDatabase()
  await db.collection('users').createIndex({ email: 1 }, { unique: true, name: 'email_unique' })
  await db.collection('users').createIndex({ 'devices.deviceId': 1 }, { name: 'device_id_index' })
  await db.collection('sessions').createIndex({ userId: 1, deviceId: 1 }, { name: 'user_device_index' })
  await db.collection('sessions').createIndex({ expiresAt: 1 }, { expireAfterSeconds: 0, name: 'session_expiry_ttl' })
  await db.collection('patients').createIndex({ userId: 1 }, { name: 'patients_user_index' })
  await db.collection('patients').createIndex({ userId: 1, patientId: 1 }, { unique: true, name: 'user_patient_unique', partialFilterExpression: { patientId: { $type: 'string' } } })
  await db.collection('files').createIndex({ userId: 1 }, { name: 'files_user_index' })
  await db.collection('files').createIndex({ userId: 1, fileId: 1 }, { unique: true, name: 'user_file_unique', partialFilterExpression: { fileId: { $type: 'string' } } })
  await db.collection('changeLogs').createIndex({ userId: 1, timestamp: -1 }, { name: 'changeLogs_user_ts' })
  await db.collection('changeLogs').createIndex({ userId: 1, entityType: 1, entityId: 1 }, { name: 'changeLogs_user_entity' })
  await db.collection('syncConflicts').createIndex({ userId: 1, isResolved: 1 }, { name: 'syncConflicts_user_resolved' })
  await db.collection('syncConflicts').createIndex({ userId: 1, timestamp: -1 }, { name: 'syncConflicts_user_ts' })
  await db.collection('chatSessions').createIndex({ sessionId: 1 }, { unique: true, name: 'chat_sessionId_unique' })
  await db.collection('chatSessions').createIndex({ userId: 1, lastUpdated: -1 }, { name: 'chat_user_lastUpdated' })
  await db.collection('chatSessions').createIndex({ patientId: 1 }, { name: 'chat_patient_index', partialFilterExpression: { patientId: { $type: 'string' } } })
  await db.collection('chatSessions').createIndex({ checksum: 1 }, { name: 'chat_checksum_index' })
  await db.collection('failedChatSessions').createIndex({ userId: 1, createdAt: -1 }, { name: 'failed_chat_user_createdAt' })
  await db.collection('failedChatSessions').createIndex({ sessionId: 1 }, { name: 'failed_chat_sessionId' })
}

export async function down(): Promise<void> {
  const db = await connectToDatabase()
  await db.collection('users').dropIndex('email_unique').catch(() => {})
  await db.collection('users').dropIndex('device_id_index').catch(() => {})
  await db.collection('sessions').dropIndex('user_device_index').catch(() => {})
  await db.collection('sessions').dropIndex('session_expiry_ttl').catch(() => {})
  await db.collection('patients').dropIndex('patients_user_index').catch(() => {})
  await db.collection('patients').dropIndex('user_patient_unique').catch(() => {})
  await db.collection('files').dropIndex('files_user_index').catch(() => {})
  await db.collection('files').dropIndex('user_file_unique').catch(() => {})
  await db.collection('changeLogs').dropIndex('changeLogs_user_ts').catch(() => {})
  await db.collection('changeLogs').dropIndex('changeLogs_user_entity').catch(() => {})
  await db.collection('syncConflicts').dropIndex('syncConflicts_user_resolved').catch(() => {})
  await db.collection('syncConflicts').dropIndex('syncConflicts_user_ts').catch(() => {})
  await db.collection('chatSessions').dropIndex('chat_sessionId_unique').catch(() => {})
  await db.collection('chatSessions').dropIndex('chat_user_lastUpdated').catch(() => {})
  await db.collection('chatSessions').dropIndex('chat_patient_index').catch(() => {})
  await db.collection('chatSessions').dropIndex('chat_checksum_index').catch(() => {})
  await db.collection('failedChatSessions').dropIndex('failed_chat_user_createdAt').catch(() => {})
  await db.collection('failedChatSessions').dropIndex('failed_chat_sessionId').catch(() => {})
}