export { SyncOrchestrator } from './sync-orchestrator'
export { syncQueue } from './sync-queue'
export { ConflictResolver } from './conflict-resolver'
export { ConflictDetector } from './conflict-detector'
export { syncService } from './sync-service'
export { sessionSyncManager, SessionSyncManager } from './session-sync-manager'
export { createSyncOrchestrator, SyncOrchestratorClient } from './sync-orchestrator-client'
export type { ConflictRecord, ResolutionResult, ResolutionStrategy } from './conflict-resolver'
export type { PendingOperation } from '@/lib/storage/unified-storage-interface'